### ISSUE TITLE
New data storage for reviews

### ISSUE THREAD

**Issue by BryceSteuer** [AndBible/andbible.github.io#13]
["Do you think this is doable to you? If not I could offer to help."](https://github.com/AndBible/andbible.github.io/pull/12#discussion_r747244819)

I think I need help with this, I understand mostly how to put the objects representing reviews into an array. The part that loses me is how to get one object (or in this case, four random unique objects at a time) and display them in HTML via the DOM. I tried 
document.getElementById("test") = reviews[1];
But I get [Object object] instead of html values. 
So if you guys wouldn't mind doing this or at least helping me out with it, that would be great. Thanks in advance

**Comment by tuomas2** [comment]
I can help, but might not be before next thursday.

**Comment by BryceSteuer** [comment]
Ok. An alternate thing I probably can do is store the data via JSON file and import it that way. At least I can look into it; I think have a plan in my mind for it that could potentially work in this scenario

**Comment by tuomas2** [comment]
Yes, array can be stored as json file too.

**Comment by tuomas2** [comment]
I did not try this, but should work:

```js
const reviews = [
    {
        content: "content of review", // no need to have html there even.
        by: "name of reviewer or initials",
        stars: 5, // default, no need to specify to every item
        source: "Google Play",  // default, no need to specify to every item
    },
    {
        content: "review 2",
        by: "Reviewer 2",
    },
];

function addReviews(parent) {
    for (const {content, by, stars = 5, source = "Google Play"} of reviews) {
        const e = document.createElement("div");
        e.classList.add("review-item");
        const star = "<span class='fa fa-star checked'></span>"
        let starStr = "";
        for (let i = 0; i < stars; i++) {
            starStr += star;
        }
        e.innerHTML = `"<i>${content}</i> <br/> <b>-${by}-, AndBible user</b> <br/> ${starStr} <small>(${source})</small><hr/>";`;
        parent.appendChild(e);
    }
}
const parent = document.getElementById("review-container");
addReviews(parent);
```

**Comment by tuomas2** [comment]
Just add id "review-container" to your div in which you want to populate review items. 

Then you can also define stylesheet for "review-item" to customize how it looks.

**Comment by tuomas2** [comment]
Oops. this just adds them all. Need to fix...

**Comment by tuomas2** [comment]
Fixed

**Comment by timbze** [comment]
`addReviews(parent, 5)` if you want 5 reviews, right? :)

**Comment by BryceSteuer** [comment]
Thanks. I think it would be four random ones though, with the featured one fixed for now at the top...

**Comment by BryceSteuer** [comment]
If you give the go ahead I can scrape up to 100 5-star reviews from Google Play to place in the object array. With light editing if necessary

**Comment by tuomas2** [comment]
anyone from dev team can could do that, and we don't need to start with 100 :-) Can add more later too.
You can start with what you have already.

**Comment by tuomas2** [comment]
@AndBible/developers

**Comment by tuomas2** [comment]
improved a bit (no need to do expensive shuffling of whole list)

**Comment by tuomas2** [comment]
Ah, now it's possible to pick 2 times same item

**Comment by tuomas2** [comment]
fixed... hopefully it works.

**Comment by BryceSteuer** [comment]
Hmm, I put that code (edited the array to include all current reviews I have) in a javascript file, linked to the file and had a 
`<div id="review-container"></div>`
But nothing renders in the div on pageload.

**Comment by tuomas2** [comment]
you must have the script loading at the end of the page. and then maybe you need to wrap the calling part with

```js
document.addEventListener('DOMContentLoaded', (event) => {
   const parent = document.getElementById("review-container");
   addReviews(parent, 5);
}
```

like you have done to your existing code.

**Comment by BryceSteuer** [comment]
Ok I've been a bit busy, sorry I didn't get back earlier.But I tried it and after a few modifications it works really well. So hopefully sometime tomorrow I can push the completed product.

**Comment by BryceSteuer** [comment]
Just [added final commit to the PR](https://github.com/AndBible/andbible.github.io/pull/12/commits/ae7b4eb33166405b2ae1bd606daedeeaeb3ff511). That should be it unless there is something I'm missing. I guess you can close this issue and the initial issue after approval and PR.

**Comment by tuomas2** [comment]
added comments

**Comment by BryceSteuer** [comment]
Should we leave this open until the Google Play scrape?

**Comment by tuomas2** [comment]
Created https://github.com/AndBible/and-bible/issues/1948 on AB side and added to my project board so it does not get forgotten. Closing this.
