### ISSUE TITLE
Host user tutorials on this site

### ISSUE THREAD

**Issue by gelafin** [AndBible/andbible.github.io#14]
I think it would be a little more modern and user-friendly to host AndBible's user tutorials on this site (if you uphold the difference between learning-focused "tutorials" and task-focused "how-to guides", these are really how-to guides).

AndBible already has a readthedocs guide using Sphinx (https://github.com/AndBible/and-bible/issues/1923) that can be published to this site.

These are the Sphinx docs showing how to publish to a GH Pages site: https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5.

**Comment by BryceSteuer** [comment]
I would like to do this.

**Comment by tuomas2** [comment]
@gelafin we have used tickets only in main repository, with different tags. I'd like to continue this way still, unless good reason to do otherwise arise. People follow that repository more closely and tickets elsewhere might be forgotten/lost.

**Comment by gelafin** [comment]
@tuomas2 Sure, thanks for letting me know!

Maybe it would help direct a few people to the right repo if there were an Issue template in this repo that just said, "Do not make Issues in this repo--use https://github.com/AndBible/and-bible/issues instead" or something?

**Comment by timbze** [comment]
Issues could even be disabled on this repo... But a issue linking to where it should be done might be better
