### ISSUE TITLE
Iconsistent usage of "AndBible" vs "And Bible" 

### ISSUE THREAD

**Issue by BryceSteuer** [AndBible/andbible.github.io#8]
Someone recently sent this to me in regard to the webpage:
       _The site looks really good! One question for you: Is ‘And Bible’ supposed to be 2 words or 1 word? Some places on this webpage show it as 2 words and other places show it as ‘AndBible’. It was a little confusing for me._
       
For instance, the header spells it "And Bible", while there are at least five and at most ten instances where it is spelled "AndBible" in the body of the HTML document. Which spelling is preferred?

**Comment by tuomas2** [comment]
"And Bible" is preferred.

BUT we might need to change name again at some point, see #1857

**Comment by timbze** [comment]
This is fixed now right? by #10. @BryceSteuer you could close it if it's done

**Comment by tuomas2** [comment]
merged, thanks!
